### PR TITLE
Emit profile change signal directly on setter

### PR DESCRIPTION
**Pull request by pvuorela**

### CODE REVIEW

**Comment by matthewvogt** [comment]
LGTM, but needs a bug reference :)

**Comment by pvuorela** [comment]
I'll add an annotation to the tag.

**Comment by spiiroin** [comment]
Too late, but.. doing it this way makes it possible for the settings app to get out of sync with what profiled actually does. When changing profile, it is unlikely that the change gets rejected but with values it can easily happen (if they are configured non-modifyable).

If the reason for this change is the small delay (100ms IIRC) profiled utilizes before broadcasting the changes, maybe we shold cut that shorter instead?

**Comment by spiiroin** [comment]
Or alternatively it might be simple enough to make profiled issue change signal anyway when some change is attempted. This way the settings app might as well assume things happen as requested and receive notification via dbus a bit later on confirming/invalidating the assumption?

**Comment by pvuorela** [comment]
This was quick fix for Lipstick regression, profile change handled differently when it happened inside event handler.

Now actually checking the code, it seems profiled code is doing blocking dbus calls, and thus I wonder how change signal is triggered late.

Blocking is a problem of it's own. UI side should never do that. Should have async variants for all profiled methods, perhaps?

**Comment by spiiroin** [comment]
The broadcast is delayed a bit so that multiple changes can be signaled at once -> multiple setter method calls can be handled and replied before any signal are sent - and from this pov it does not matter whether client uses blocking or async calls. Been a while, but possibly this was done to avoid dbus noise resulting from how n900 settings app behaved - it cached all changes and emitted them at once on exit, accept click or something like that.

**Pull request merged**
